services:
  stock:
    build:
      # context: https://github.com/RSO-2024-25-skupina-03/stock.git
      context: ../stock
    container_name: rso_stock
    ports:
      - "8000:8080"

  orders:
    build:
      context: ../orders
    container_name: rso_orders
    ports:
      - "8001:3000"
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongo:27017/Orders
    depends_on:
      - mongo
      - rabbitmq
    
  authentication:
    build:
      context: ../authentication
    container_name: rso_authentication
    ports:
      - "8004:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongo:27017/Authentication
      - JWT_SECRET=superSecretPassword

  mongo:
    image: mongo
    container_name: rso_mongo

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rso_rabbitmq
    ports:
      - "15672:15672"

  test-order-producer:
    build:
      context: ../test-order-producer
    container_name: rso_test_order_producer
    ports:
      - "8002:8080"

  cart:
    build:
      context: ../cart
    container_name: rso_cart
    ports:
      - "8003:8080"
