services:
  stock:
    build:
      # context: https://github.com/RSO-2024-25-skupina-03/stock.git
      context: ../stock
    container_name: rso_stock
    networks:
      - prometheus
    ports:
      - "8000:8080"

  orders:
    build:
      context: ../orders
    container_name: rso_orders
    networks:
      - prometheus
    ports:
      - "8001:3000"
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongo:27017/Orders
    depends_on:
      - mongo
      - rabbitmq

  cart:
    build:
      context: ../cart
    container_name: rso_cart
    networks:
      - prometheus
    ports:
      - "8002:8080"

  authentication:
    build:
      context: ../authentication
    container_name: rso_authentication
    networks:
      - prometheus
    ports:
      - "8003:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongo:27017/Authentication
      - JWT_SECRET=superSecretPassword

  mongo:
    image: mongo
    networks:
      - prometheus
    container_name: rso_mongo

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rso_rabbitmq
    networks:
      - prometheus
    ports:
      - "15672:15672"

  prometheus:
    build:
      context: ../prometheus
    container_name: rso_prometheus
    networks:
      - prometheus
    ports:
      - "9090:9090"

  loki:
    build:
      context: ../loki
    container_name: rso_loki
    environment:
      config.file: /etc/loki_config.yml
    networks:
      - prometheus
    ports:
      - "3100:3100"

  grafana:
    build:
      context: ../grafana
    container_name: rso_grafana
    environment:
      - GF_LOG_LEVEL=debug
    networks:
      - prometheus
    ports:
      - "3000:3000"
networks:
  prometheus:
    driver: bridge
