apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)

  labels:
    io.kompose.service: authentication
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authentication
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)

      labels:
        io.kompose.service: authentication
    spec:
      containers:
        - env:
            - name: ADMIN_KEY
              value: superAdminKey
            - name: DOMAIN
              value: '*domain'
            - name: JWT_SECRET
              value: superSecretPassword
            - name: MONGODB_URI
              value: mongodb://mongo:27017/Authentication
            - name: NODE_ENV
              value: '*node_env'
          image: authentication
          livenessProbe:
            exec:
              command:
                - curl -f http://authentication:3000/
          name: rso-authentication
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
