apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
    traefik.enable: "true"
    traefik.http.middlewares.cart-strip.stripPrefix.prefixes: /api/cart
    traefik.http.routers.cart.entrypoints: web
    traefik.http.routers.cart.middlewares: cart-strip
    traefik.http.routers.cart.rule: PathPrefix(`/api/cart`)
  labels:
    io.kompose.service: cart
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cart
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)

      labels:
        io.kompose.service: cart
    spec:
      containers:
        - image: cart
          livenessProbe:
            exec:
              command:
                - curl -f http://cart:8080/
          name: rso-cart
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
