apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo
          name: rso-mongo
      restartPolicy: Always
