apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
    traefik.enable: "true"
    traefik.http.middlewares.orders-strip.stripPrefix.prefixes: /api/orders
    traefik.http.routers.orders.entrypoints: web
    traefik.http.routers.orders.middlewares: orders-strip
    traefik.http.routers.orders.rule: PathPrefix(`/api/orders`)
  labels:
    io.kompose.service: orders
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orders
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)

      labels:
        io.kompose.service: orders
    spec:
      containers:
        - env:
            - name: DOMAIN
              value: '*domain'
            - name: MONGODB_URI
              value: mongodb://mongo:27017/Orders
            - name: NODE_ENV
              value: '*node_env'
          image: orders
          livenessProbe:
            exec:
              command:
                - curl -f http://orders:3000/
          name: rso-orders
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
