apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)

  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)

      labels:
        io.kompose.service: prometheus
    spec:
      containers:
        - image: prometheus
          name: rso-prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
      restartPolicy: Always
