apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)

  labels:
    io.kompose.service: stock
  name: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stock
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)

      labels:
        io.kompose.service: stock
    spec:
      containers:
        - image: stock
          livenessProbe:
            exec:
              command:
                - curl -f http://stock:8080/
          name: rso-stock
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
